version: '3'
services:
  web:
    build: ./web
    ports:
     - "8000:80"
  database:
    build: ./database
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
